services:
  db:
    image: postgres:17
    container_name: sparrow_db
    environment:
      POSTGRES_USER: sparrow
      POSTGRES_PASSWORD: sparrow_password
      POSTGRES_DB: sparrow_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
